laika.title = Compliance

laika.navigationOrder = [
  baggage.md
  resource.md
  instrumentation-scope.md
  logs.md
  metrics.md
  trace.md
  context-propagation.md
  configuration.md
  compliance-matrix.md
]
