laika.title = Specification Compliance

laika.navigationOrder = [
  attributes.md
  baggage.md
  resource.md
  instrumentation-scope.md
  context.md
  context-propagation.md
  logs.md
  metrics.md
  trace.md
  configuration.md
  compliance-matrix.md
]
